version: "3"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: wcnm741741..
    volumes:
      - /docker/rabbitmq/data:/var/lib/rabbitmq
      - /docker/rabbitmq/conf:/etc/rabbitmq
    restart: always
