version: "3.1"
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: always
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /docker/jenkins/data/:/var/jenkins_home/
    environment:
      JAVA_OPTS: "-Djava.util.logging.config.file=/var/jenkins_home/log.properties"
