{
 "title": "Nacos",
 "description": "Nacos grafana dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "nacos monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nacos_monitor{name=\"configCount\"})"
    }
   ]
  },
  {
   "title": "service count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nacos_monitor{name='serviceCount'})"
    }
   ]
  },
  {
   "title": "ip count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nacos_monitor{name='ipCount'})"
    }
   ]
  },
  {
   "title": "config count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nacos_monitor{name='configCount', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "long polling",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='longPolling'})"
    }
   ]
  },
  {
   "title": "config push total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='getConfig', instance=~'$instance'}) by (name)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": {
    "content": "<center>\n  <a href=\"https://nacos.io\">\n    <img src=\"https://s1.ax1x.com/2020/10/22/BiuZRO.png\" style=\"height: 50px; margin-top:20px\" />\n  </a>\n</center>"
   }
  },
  {
   "title": "cpu",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(system_cpu_usage{instance=~'$instance'}) * 100"
    }
   ]
  },
  {
   "title": "memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", instance=~'$instance'})/sum(jvm_memory_max_bytes{area=\"heap\", instance=~'$instance'}) * 100"
    }
   ]
  },
  { "title": "alert list", "type": "alertlist", "gridPos": { "h": 16, "w": 6, "x": 18, "y": 4 } },
  {
   "title": "threads",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_threads_daemon_threads{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(system_load_average_1m{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "notify rt",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nacos_timer_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(nacos_timer_seconds_count{instance=~'$instance'}[1m])) * 1000"
    }
   ]
  },
  {
   "title": "rt",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m])) * 1000"
    }
   ]
  },
  {
   "title": "qps",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m]))"
    }
   ]
  },
  {
   "title": "avgPushCost",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nacos_monitor{name='avgPushCost', instance=~'$instance'})"
    }
   ]
  },
  { "title": "nacos detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "rt",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=~'/v1/cs/configs|/nacos/v1/ns', instance=~'$instance'}[1m])/rate(http_server_requests_seconds_count{uri=~'/v1/cs/configs|/nacos/v1/ns/instance|/nacos/v1/ns/health', instance=~'$instance'}[1m])) by (method,uri) * 1000"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m])) * 1000",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "long polling",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
   "repeat": "group",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='longPolling', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "load 1m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(system_load_average_1m{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "qps",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~'/v1/cs/configs|/nacos/v1/ns/instance|/nacos/v1/ns/health', instance=~'$instance'}[1m])) by (method,uri)"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "leaderStatus",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='leaderStatus', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "avgPushCost",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='avgPushCost', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "maxPushCost",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(nacos_monitor{name='maxPushCost', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "config statistics",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='publish', instance=~'$instance'}) by (name)",
     "legendFormat": "publish config"
    },
    {
     "expr": "sum(nacos_monitor{name='getConfig', instance=~'$instance'}) by (name)",
     "legendFormat": "get config"
    }
   ]
  },
  {
   "title": "health check",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_monitor{name=~'.*HealthCheck', instance=~'$instance'}[1m])) by (name) * 60"
    }
   ]
  },
  { "title": "nacos alert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "cpu alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(system_cpu_usage) * 100" }
   ]
  },
  {
   "title": "load  alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(system_load_average_1m)" }
   ]
  },
  {
   "title": "memory alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})/sum(jvm_memory_max_bytes{area=\"heap\"}) * 100"
    }
   ]
  },
  {
   "title": "threads alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(jvm_threads_daemon_threads)"
    }
   ]
  },
  {
   "title": "gc alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(jvm_gc_pause_seconds_count{action=\"end of major GC\"}[5m])) * 300"
    }
   ]
  },
  {
   "title": "notify task alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='notifyTask'})"
    }
   ]
  },
  {
   "title": "rt alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum[1m]))/sum(rate(http_server_requests_seconds_count[1m])) * 1000"
    }
   ]
  },
  {
   "title": "long polling alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(nacos_monitor{name='longPolling'})"
    }
   ]
  },
  {
   "title": "config unhealth exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='unhealth'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "db exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='db'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "failed push alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='failedPush'})"
    }
   ]
  },
  {
   "title": "illegalArgument exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='illegalArgument'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "naming disk exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='disk'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "config notify exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='configNotify'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "naming leader send beat failed exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='leaderSendBeatFailed'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "nacos exception alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='nacos'}[1m])) * 60"
    }
   ]
  }
 ]
}